# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email_parent', models.EmailField(blank=True, max_length=254, verbose_name='Email du parent')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_eleves/', verbose_name='Photo')),
                ('est_orphelin', models.BooleanField(default=False, verbose_name='Orphelin')),
                ('est_boursier', models.BooleanField(default=False, verbose_name='Boursier')),
                ('est_handicape', models.BooleanField(default=False, verbose_name='Handicapé')),
                ('est_pris_en_charge', models.BooleanField(default=False, verbose_name='Pris en charge')),
                ('est_cas_social', models.BooleanField(default=False, verbose_name='Cas social')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.classe', verbose_name='Classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
        ),
    ]
