# Generated by Django 6.0.2 on 2026-02-18 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_boursier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_cas_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_handicape',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_orphelin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_pris_en_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_eleves/'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
