# Generated by Django 5.2.6 on 2026-02-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.classe', verbose_name='Classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du parent'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_boursier',
            field=models.BooleanField(default=False, verbose_name='Boursier'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_cas_social',
            field=models.BooleanField(default=False, verbose_name='Cas social'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_handicape',
            field=models.BooleanField(default=False, verbose_name='Handicapé'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_orphelin',
            field=models.BooleanField(default=False, verbose_name='Orphelin'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='est_pris_en_charge',
            field=models.BooleanField(default=False, verbose_name='Pris en charge'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_eleves/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
