# Generated by Django 6.0.2 on 2026-02-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=20)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('capacite', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
