# Generated by Django 6.0.2 on 2026-02-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('enseignants', '0002_remove_enseignant_matiere_principale_and_more'),
        ('parametres', '0002_niveauscolaire_option_periode_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de la salle')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('equipement', models.TextField(blank=True, verbose_name='Équipement disponible')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau__categorie', 'niveau__ordre', 'nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='classe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='parametres.option', verbose_name='Option (humanités)'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='enseignants.enseignant', verbose_name='Professeur principal'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='parametres.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='capacite',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='parametres.niveauscolaire', verbose_name='Niveau scolaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(help_text='Ex: 6ème A, 1ère Bio-chimie, etc.', max_length=50, verbose_name='Nom de la classe'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_scolaire', 'niveau', 'option')},
        ),
    ]
