# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'verbose_name_plural': 'Catégories de frais',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('categorie', models.CharField(blank=True, max_length=50, verbose_name='Catégorie (optionnelle)')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du frais')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('echeance', models.DateField(verbose_name='Échéance')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='finance.categoriefrais', verbose_name='Catégorie')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='parametres.periode', verbose_name='Période concernée')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('recu_genere', models.BooleanField(default=False, verbose_name='Reçu généré')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve', verbose_name='Élève')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.frais', verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
