# Generated by Django 6.0.2 on 2026-02-18 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
        ('finance', '0001_initial'),
        ('parametres', '0002_niveauscolaire_option_periode_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='frais',
            options={'ordering': ['echeance'], 'verbose_name': 'Frais', 'verbose_name_plural': 'Frais'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='depense',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='depenses/'),
        ),
        migrations.AddField(
            model_name='frais',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categoriefrais',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='frais',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='finance.categoriefrais'),
        ),
        migrations.AlterField(
            model_name='frais',
            name='echeance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='frais',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='frais',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frais',
            name='obligatoire',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frais',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='parametres.periode'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.frais'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='recu_genere',
            field=models.BooleanField(default=False),
        ),
    ]
