# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('cours', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('salle', models.CharField(blank=True, max_length=20, verbose_name='Salle')),
                ('annee_scolaire', models.CharField(blank=True, max_length=9, verbose_name='Année scolaire (ex: 2024-2025)')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='classes.classe', verbose_name='Classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='cours.cours', verbose_name='Cours')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires', to='enseignants.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('classe', 'jour', 'heure_debut'), ('enseignant', 'jour', 'heure_debut')},
            },
        ),
    ]
