# Generated by Django 6.0.2 on 2026-02-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('cours', '0002_alter_cours_unique_together_alter_cours_enseignant_and_more'),
        ('enseignants', '0002_remove_enseignant_matiere_principale_and_more'),
        ('horaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='annee_scolaire',
        ),
        migrations.AlterField(
            model_name='horaire',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='cours.cours'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires', to='enseignants.enseignant'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='heure_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='salle',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
