# Generated by Django 6.0.2 on 2026-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 1ère maternelle, 6ème primaire, 1ère humanité...', max_length=50, verbose_name='Nom du niveau')),
                ('categorie', models.CharField(choices=[('maternel', 'École Maternelle (1-4 ans)'), ('primaire', 'École Primaire (1-6)'), ('base', 'École de Base (7-8)'), ('humanite', 'Humanités (1-4)')], max_length=20, verbose_name='Catégorie')),
                ('ordre', models.PositiveIntegerField(help_text='1,2,3... pour trier les niveaux', verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'option")),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Période active'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='active',
            field=models.BooleanField(default=False, help_text='Une seule année peut être active à la fois', verbose_name='Année active'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='nom',
            field=models.CharField(help_text='Format: 2024-2025', max_length=9, unique=True, verbose_name='Année scolaire'),
        ),
    ]
