# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets_actifs', models.JSONField(blank=True, default=list, verbose_name='Widgets actifs')),
                ('mise_en_page', models.CharField(choices=[('grille', 'Grille'), ('liste', 'Liste'), ('compact', 'Compact')], default='grille', max_length=20, verbose_name='Mise en page')),
                ('couleur_theme', models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre'), ('automatique', 'Automatique')], default='clair', max_length=20, verbose_name='Thème de couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence du tableau de bord',
                'verbose_name_plural': 'Préférences du tableau de bord',
            },
        ),
    ]
