# Generated by Django 6.0.2 on 2026-02-18 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardpreference',
            name='couleur_theme',
        ),
        migrations.RemoveField(
            model_name='dashboardpreference',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='dashboardpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardpreference',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardpreference',
            name='widgets_ordre',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardpreference',
            name='mise_en_page',
            field=models.CharField(choices=[('grille', 'Grille'), ('liste', 'Liste'), ('compact', 'Compact')], default='grille', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardpreference',
            name='widgets_actifs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
