# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date de l'incident")),
                ('type', models.CharField(choices=[('avertissement', 'Avertissement'), ('blâme', 'Blâme'), ('exclusion_temporaire', 'Exclusion temporaire'), ('exclusion_definitive', 'Exclusion définitive'), ('autre', 'Autre')], max_length=25, verbose_name='Type')),
                ('description', models.TextField(verbose_name="Description de l'incident")),
                ('sanction', models.TextField(blank=True, verbose_name='Sanction appliquée')),
                ('duree_exclusion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Durée d'exclusion (en jours)")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('rapporte_par', models.CharField(blank=True, max_length=100, verbose_name='Rapporté par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Incident disciplinaire',
                'verbose_name_plural': 'Incidents disciplinaires',
                'ordering': ['-date', 'eleve'],
            },
        ),
    ]
