# Generated by Django 6.0.2 on 2026-02-18 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date'], 'verbose_name': 'Incident disciplinaire', 'verbose_name_plural': 'Incidents disciplinaires'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='duree_exclusion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='eleves.eleve'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='rapporte_par',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sanction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('avertissement', 'Avertissement'), ('blâme', 'Blâme'), ('exclusion_temporaire', 'Exclusion temporaire'), ('exclusion_definitive', 'Exclusion définitive'), ('autre', 'Autre')], max_length=25),
        ),
    ]
