# Generated by Django 5.2.6 on 2026-02-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0003_alter_eleve_adresse_alter_eleve_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('enfants', models.ManyToManyField(related_name='parents', to='eleves.eleve', verbose_name='Enfants')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
    ]
