# Generated by Django 6.0.2 on 2026-02-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_alter_cours_unique_together_alter_cours_enseignant_and_more'),
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('justifie', 'Absence justifiée')], default='present', max_length=10, verbose_name='Statut')),
                ('justificatif', models.TextField(blank=True, verbose_name='Justificatif')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='cours.cours', verbose_name='Cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('eleve', 'cours', 'date')},
            },
        ),
    ]
