# Generated by Django 5.2.6 on 2026-02-19 19:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('cours', '0003_alter_cours_options_cours_annee_scolaire_and_more'),
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('exclu', 'Exclu'), ('malade', 'Malade'), ('autorise', 'Absence autorisée')], default='present', max_length=10, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif (si absence/retard/exclusion)')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', 'eleve__nom'],
                'unique_together': {('eleve', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PresenceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('est_verrouille', models.BooleanField(default=False, verbose_name='Pointage verrouillé')),
                ('date_verrouillage', models.DateTimeField(blank=True, null=True, verbose_name='Date de verrouillage')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_journalieres', to='classes.classe', verbose_name='Classe')),
                ('cours_du_jour', models.ManyToManyField(related_name='presences_journalieres', to='cours.cours', verbose_name='Cours du jour')),
            ],
            options={
                'verbose_name': 'Présence journalière',
                'verbose_name_plural': 'Présences journalières',
                'unique_together': {('classe', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
