# Generated by Django 6.0.2 on 2026-02-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du cours')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='classes.classe', verbose_name='Classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='enseignants.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'unique_together': {('classe', 'nom')},
            },
        ),
    ]
