# Generated by Django 6.0.2 on 2026-02-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('cours', '0001_initial'),
        ('enseignants', '0002_remove_enseignant_matiere_principale_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours_enseignes', to='enseignants.enseignant', verbose_name='Enseignant'),
        ),
        migrations.CreateModel(
            name='ProgrammeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('heures_semaine', models.PositiveIntegerField(default=0)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
            ],
            options={
                'verbose_name': 'Programme de classe',
                'verbose_name_plural': 'Programmes de classe',
                'unique_together': {('classe', 'cours')},
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='classes',
            field=models.ManyToManyField(related_name='cours_programmes', through='cours.ProgrammeClasse', to='classes.classe', verbose_name='Classes'),
        ),
        migrations.RemoveField(
            model_name='cours',
            name='classe',
        ),
    ]
