# Generated by Django 5.2.6 on 2026-02-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_salle_alter_classe_options_classe_date_creation_and_more'),
        ('cours', '0002_alter_cours_unique_together_alter_cours_enseignant_and_more'),
        ('parametres', '0002_niveauscolaire_option_periode_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['niveau', 'nom'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AddField(
            model_name='cours',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='parametres.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(blank=True, help_text='Niveau concerné par ce cours', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='parametres.niveauscolaire', verbose_name='Niveau scolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='option',
            field=models.ForeignKey(blank=True, help_text='Option pour Base/Humanités', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='parametres.option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='cours_programmes', through='cours.ProgrammeClasse', to='classes.classe', verbose_name='Classes spécifiques'),
        ),
        migrations.AlterField(
            model_name='programmeclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='programmeclasse',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='programmeclasse',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='cours.cours'),
        ),
        migrations.AlterField(
            model_name='programmeclasse',
            name='heures_semaine',
            field=models.PositiveIntegerField(default=0, verbose_name='Heures par semaine'),
        ),
    ]
