# Generated by Django 6.0.2 on 2026-02-18 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere_principale',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('titulaire', 'Titulaire de classe'), ('adjoint', 'Adjoint/Co-enseignant'), ('professeur', 'Professeur par heure')], default='professeur', max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_embauche',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='lieu_naissance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_enseignants/'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
