# Generated by Django 6.0.2 on 2026-02-18 20:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_alter_cours_unique_together_alter_cours_enseignant_and_more'),
        ('eleves', '0002_alter_eleve_adresse_alter_eleve_classe_and_more'),
        ('enseignants', '0002_remove_enseignant_matiere_principale_and_more'),
        ('parametres', '0002_niveauscolaire_option_periode_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('date_edition', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='parametres.periode')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'unique_together': {('eleve', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('appreciation', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='cours.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='eleves.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='enseignants.enseignant')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='parametres.periode')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['periode', 'cours', 'eleve'],
                'unique_together': {('eleve', 'cours', 'periode')},
            },
        ),
    ]
