# Generated by Django 6.0.2 on 2026-02-20 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_options_cours_annee_scolaire_and_more'),
        ('eleves', '0003_alter_eleve_adresse_alter_eleve_classe_and_more'),
        ('enseignants', '0002_remove_enseignant_matiere_principale_and_more'),
        ('parametres', '0002_niveauscolaire_option_periode_active_and_more'),
        ('resultats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['periode', '-moyenne_generale'], 'verbose_name': 'Bulletin', 'verbose_name_plural': 'Bulletins'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'ordering': ['periode', 'cours', '-note'], 'verbose_name': 'Résultat', 'verbose_name_plural': 'Résultats'},
        ),
        migrations.AddField(
            model_name='bulletin',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='total_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total des points'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='parametres.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='rang',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='date_edition',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'édition"),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve', verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='moyenne_generale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne générale'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Bulletin PDF'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='parametres.periode', verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='rang',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='appreciation',
            field=models.TextField(blank=True, verbose_name='Appréciation'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='cours.cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='eleves.eleve', verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='enseignants.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note /20'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='parametres.periode', verbose_name='Période'),
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(choices=[('TB', 'Très Bien'), ('B', 'Bien'), ('AB', 'Assez Bien'), ('P', 'Passable'), ('I', 'Insuffisant')], max_length=2, verbose_name='Mention')),
                ('date_obtention', models.DateField(auto_now_add=True, verbose_name="Date d'obtention")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='eleves.eleve', verbose_name='Élève')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='parametres.periode', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'unique_together': {('eleve', 'periode')},
            },
        ),
    ]
